### PR TITLE
bug: Select dropdown label bug

### PR DESCRIPTION
**Pull request by tpszhao**
Issue #113 

I'm using yarn 3.2.1

added .yarn in .gitignore
.yarnrc.yml is auto-generated

### CODE REVIEW

**Comment by wtLau** [comment]
I think the changes for `.yarn in .gitignore` are not needed here.  @tpszhao 

How did you run the install? I am not sure if it should create new files... 🤣

**Comment by tpszhao** [comment]
I think it might be caused by the yarn versions? 
All I did was cd into the directory, and those files are modified automatically. 
It also created a `.yarn` directory which I put in the gitignore

**Comment by wtLau** [comment]
@tpszhao  hey, do you mind reverting the changes to yarn for this PR?

I think I'll try to fix that in another PR. Just to want to keep the PR cleaner

**Comment by tpszhao** [comment]
> @tpszhao hey, do you mind reverting the changes to yarn for this PR?
> 
> I think I'll try to fix that in another PR. Just to want to keep the PR cleaner

@wtLau  done!

**Pull request merged**
